Create Database SQLDemoDB;
Use SQLDemoDB;

--Create Table Using DataType And Constraints
--Bit – store bit data i.e., 0, 1, or NULL
--int – store integer types in SQL server including BIGINT(8byte), INT(4byte), SMALLINT(2byte), and TINYINT(1).
CREATE TABLE Test_integers (
	bigint_col bigint,
	int_col INT,
	smallint_col SMALLINT,
	tinyint_col tinyint
);

--Drop Delete Object Table
Drop table Test_integers;
--DECIMAL – store  DECIMAL
--CHAR(1byte) – to store fixed-length, non-Unicode 
--NCHAR(2byte) –  store fixed-length, Unicode character 
--VARCHAR – store variable-length, non-Unicode string data
--NVARCHAR – to store variable-length, Unicode string data
Create Table Varchar_Table (
Gender char,
Name varchar(30)
);

--DATETIME2 – to store both date and time data in a database.
--we use CURRENT_TIMESTAMP as the default value DateTime2 also GetDate() method use for insert date time
Create table Published(
Create_At DateTime2(3) 
);
insert into Published values(GETDATE());
select* from Published;

ALTER TABLE Published
ADD CONSTRAINT df_current_time 
DEFAULT CURRENT_TIMESTAMP FOR Create_At;


--DATE – discuss the date data type and how to store the dates in the table.
--TIME – show you how to store time data in the database by using the TIME data type.

--A GUID is guaranteed to be unique across tables, databases, and even servers.
--In SQL Server, GUID is 16-byte binary data type, which is generated by using the NEWID() function:UNIQUEIDENTIFIER data type holds GUID values.

--Constraints
--Primary key  – Unique +Not null
--Foreign key - refer as primary key to anothe table
--NOT NULL constraint – to ensure a column not to accept NULL.
--UNIQUE constraint – data is unique among row
--CHECK constraint – checking data before storing them
CREATE TABLE Product(
    productId INT IDENTITY PRIMARY KEY,
    productName VARCHAR(255) NOT NULL,
    Price DEC(10,2) CONSTRAINT positive_price CHECK(Price > 0)
)
INSERT INTO Product(productName, Price)
VALUES ('Bag', 10);

INSERT INTO Product
VALUES ('Bag', 10);
--Multiple Row Added
INSERT INTO Product(productName, Price)
VALUES ('ring', 10),('watch',30),('skincareProduct',30);
SELECT * FROM Product;
Drop table Product;

--DDL -data defination lang(used to create ,modify the object and structure)
--create(new create),alter(update object ),drop(delete object),truncate(data delete but not structure),rename(rename the object)
--Create(Database,Table,View,Triggers)
--Alter (table modifing by adding .altering,dropping column and constraints)

      --Adding New Column
Alter Table Product ADD Quantity int default 1;
         ALTER TABLE Product
         ADD DateOfBirth date;

      --Droping Column
	ALTER TABLE Product
DROP COLUMN Quantity ;

--Rename Column
--RENAME old_table _name To new_table_name ;    
   --MODIFY DATATYPE
  ALTER TABLE Product
  ALTER COLUMN DateOfBirth DateTime; 

  --Turncate (Delete all row )
  TRUNCATE TABLE Product;

